# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/anatexis.github.io',
                'doc_host': 'https://anatexis.github.io',
                'git_url': 'https://github.com/anatexis/anatexis.github.io',
                'lib_path': 'anatexis.github.io'},
  'syms': {}}
