project:
  type: website

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

website:
  title: "Christoph Kugler"
  site-url: https://anatexis.github.io/
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    search: true
    right:
      - text: Blog
        href: blog/index.qmd
      - icon: github
        href: "https://github.com/anatexis"
      - icon: twitter
        href: "https://twitter.com/_anatexis_"
        aria-label: Christoph K. Twitter
  sidebar:
    style: floating

# metadata-files: [nbdev.yml, sidebar.yml]
